### ISSUE TITLE
Not working on RHEL 6 with firefox 38

### ISSUE THREAD

**Issue by eobu** [fwenzel/ciaociao#12]
When clicking its button, it immediately says "No services found!".  I'm a using avahi-publish to send out _http._tcp dns-sd service announcements, and avahi-browse sees them.  I am assuming ciaociao won't work with such an old version of firefox, but wanted to check with you on this.

**Comment by fwenzel** [comment]
It *might* be the Firefox version, I do not know. It could also be the path:

https://github.com/fwenzel/ciaociao/blob/master/src/lib/services/avahi.js#L7

We're expecting it to be on `/usr/bin`. Where is your binary? You can look at the browser console and perhaps catch an error message.

**Comment by fwenzel** [comment]
Closing this for now: The file is available in the expected location as shown here: https://www.rpmfind.net/linux/RPM/fedora/devel/rawhide/x86_64/a/avahi-tools-0.7-6.fc28.x86_64.html

Please reopen if you have more info!
