### ISSUE TITLE
text is not un-escaped

### ISSUE THREAD

**Issue by davecotter** [fwenzel/ciaociao#5]
any bonjour service with a space in it shows the space as "/032" instead of just " ".  note that it only happens after the FIRST space (which is shown correctly).  

![screen shot 2015-02-16 at 10 12 52 am](https://cloud.githubusercontent.com/assets/259854/6217021/618544ec-b5c4-11e4-847e-b318a40107ed.png)

**Comment by fwenzel** [comment]
oooooh, that it happens for all but the first space is a sufficient error description, now I can find the bug :) thank you

**Comment by davecotter** [comment]
awesome!  also note that some services are listed twice (?)

**Comment by fwenzel** [comment]
Odd how there are duplicates -- I filed another issue to look if this is actually twice in your device list, or if that's a bug in ciaociao!
