### ISSUE TITLE
Use dns-sd.js to make add-on cross-platform

### ISSUE THREAD

**Issue by fwenzel** [fwenzel/ciaociao#7]
Thanks @supersole for [today's blog post](http://soledadpenades.com/2015/04/08/front-end-mdns-announcing-and-finding-network-services-with-javascript/).

[dns-sd.js](https://github.com/justindarc/dns-sd.js) exists, is MIT licensed, so we should be able to use that rather than parsing out command line output on Mac only. Marvelous!

**Comment by JonTheNiceGuy** [comment]
What can I do to help make this happen? :)

**Comment by rjsteinert** [comment]
> It uses some Firefox OS-only APIs such as mozTCPSocket, so it only runs on Gecko/Gaia environments

My guts tell me that every new platform will need a mozTCPSocket equivalent.

**Comment by fwenzel** [comment]
Yes that's correct. With Firefox OS on phones not being a Thing anymore, I can't just add dns-sd.js and it'll magically work. In particular, it would only work on Firefox OS, but not on Firefox for Windows etc.

**Comment by fwenzel** [comment]
I'm closing this because I did not find an API in Firefox (not: OS) that I would be able to connect to this. It would be most lovely not having to shell out to external tools, alas we have to.
