### ISSUE TITLE
avahi support

### ISSUE THREAD

**Issue by chrysn** [fwenzel/ciaociao#8]
given the approach in #7 does not look promising right now due to platform considerations, i'd like to suggest another path: the `avahi-browse` utility seems to do on free unix systems roughly what dns-sd is doing on osx. an invocation of `avahi-browse _http._tcp --resolve --parsable --no-db-lookup --terminate` gives me:

    +;wlan0;IPv4;my-server;_http._tcp;local
    +;wlan0;IPv4;MPC\032client\032on\032my-server;_http._tcp;local
    =;wlan0;IPv4;my-server;_http._tcp;local;my-server.local;10.13.13.227;80;"path=/storage/"
    =;wlan0;IPv4;MPC\032client\032on\032my-server;_http._tcp;local;my-server.local;10.13.13.227;6680;

(without --resolve, it would only show the `+` lines and not dig down deep enough to give the details in the `=` records).

would you consider adding support for those platforms?

**Comment by fwenzel** [comment]
Yes, I would. Thanks a LOT for suggesting this. I find this very exciting. (Note, I'll have to spin up a Linux VM to test, but either way this is great!)

**Comment by fwenzel** [comment]
I gave it a quick and dirty shot (if you're interested in the work in progress code: https://github.com/fwenzel/ciaociao/commit/0fe02c3022eef892f85f1cfb72c4364131df614b). That appears to work. Neat!

I think I'll clean up the architecture of this a bit (don't really want to check avahi/dnssd repeatedly) and then I'll have to check with an actual Linux system but so far so good!

**Comment by chrysn** [comment]
> I gave it a quick and dirty shot (if you're interested in the work in
> progress code:
> https://github.com/fwenzel/ciaociao/commit/0fe02c3022eef892f85f1cfb72c4364131df614b).

i've run it with `jpm run`. on the first click to the globe icon, no
services are discovered (more or less reproducible by running
`/etc/init.d/avahi-daemon restart` or similar). on later clicks, it
worked!

having the code print each .on('data') event, it seems that "no results"
are shown when data comes in in multiple segments, compare


console.info: ciaociao: spawning avahi
console.info: ciaociao: parsing +;wlan0;IPv4;my-server;_http._tcp;local
+;wlan0;IPv4;some\032daemon\032on\032my-server;_http._tcp;local
=;wlan0;IPv4;my-server;_http._tcp;local;my-server.local;192.168.0.2;80;"path=/films/"
=;wlan0;IPv4;some\032daemon\032on\032my-server;_http._tcp;local;my-server.local;192.168.0.2;8080;
 constructor {}
console.info: ciaociao: kill timeout

(which worked) vs

console.info: ciaociao: spawning avahi
console.info: ciaociao: parsing +;wlan0;IPv4;some\032daemon\032on\032my-server;_http._tcp;local
 constructor {}
console.info: ciaociao: parsing +;wlan0;IPv4;my-server;_http._tcp;local
=;wlan0;IPv4;some\032daemon\032on\032my-server;_http._tcp;local constructor {}
console.info: ciaociao: parsing ;my-server.local;192.168.0.2;8080;
=;wlan0;IPv4;my-server;_http._tcp;local constructor {}
console.info: ciaociao: parsing ;my-server.local;192.168.0.2;80;"path=/films/"
 constructor {}
console.info: ciaociao: kill timeout

(which didn't work).

> I think I'll clean up the architecture of this a bit (don't really
> want to check avahi/dnssd repeatedly)

at least avahi can do that; as long as --terminate is not given, it
seems to run forever. when a services disappears and reappears, it looks
like this:

+;wlan0;IPv4;my-server;_http._tcp;local
+;wlan0;IPv4;some\032daemon\032on\032my-server;_http._tcp;local
=;wlan0;IPv4;my-server;_http._tcp;local;my-server.local;192.168.0.2;80;"path=/films/"
=;wlan0;IPv4;some\032daemon\032on\032my-server;_http._tcp;local;my-server.local;192.168.0.2;8080;
[...time passes...]
-;wlan0;IPv4;some\032daemon\032on\032my-server;_http._tcp;local
[...time passes again...]
+;wlan0;IPv4;some\032daemon\032on\032my-server;_http._tcp;local
=;wlan0;IPv4;some\032daemon\032on\032my-server;_http._tcp;local;my-server.local;192.168.0.2;8080;

thanks for taking this up
chrysn

**Comment by fwenzel** [comment]
Thank you this is super useful.

1) I do want it to work when info comes in in chunks, that's how I tried to design it anyway (and that means I can increase the timeout to, say, 10 seconds and you'll see results immediately as they're discovered. I *could* certainly keep it running until you close the dropdown (as opposed to cutting it off after 5 seconds).

2) sounds like I'll need to write tests for the parsers anyway to catch this.

**Comment by fwenzel** [comment]
I wrote test, but put the timeout piece into a separate Issue #9.

**Comment by fwenzel** [comment]
I submitted version 2.0.0 to AMO for review! https://addons.mozilla.org/en-US/firefox/addon/ciaociao/versions/?page=1#version-2.0.0

**Comment by fwenzel** [comment]
PS: If you have ideas for Windows, I filed Issue #10 and would love input.
